### PR TITLE
Add option to run docker container as root user (fixes #57)

### LINKED ISSUE #57: Docker and ownership permissions
Hi, I store my models on a local NAS, synology - which does not allow me to change ownership permissions of the files.

I get the following error when starting up the docker container with docker compose;

```
 ⠿ Network exllama_default  Created                                                                                                                                                                0.0s 
 ⠿ Container exllama-web-1  Created                                                                                                                                                                0.1s
Attaching to exllama-web-1
exllama-web-1  | chown: changing ownership of '/app/model/minotaur-13b-GPTQ-4bit-128g.no-act.order.safetensors': Operation not permitted
exllama-web-1  | chown: changing ownership of '/app/model/tokenizer.model': Operation not permitted
exllama-web-1  | chown: changing ownership of '/app/model/tokenizer_config.json': Operation not permitted
exllama-web-1  | chown: changing ownership of '/app/model/tokenizer.json': Operation not permitted
exllama-web-1  | chown: changing ownership of '/app/model/special_tokens_map.json': Operation not permitted
exllama-web-1  | chown: changing ownership of '/app/model/quantize_config.json': Operation not permitted
exllama-web-1  | chown: changing ownership of '/app/model/generation_config.json': Operation not permitted
exllama-web-1  | chown: changing ownership of '/app/model/config.json': Operation not permitted
exllama-web-1  | chown: changing ownership of '/app/model/README.md': Operation not permitted
exllama-web-1  | chown: changing ownership of '/app/model': Operation not permitted
exllama-web-1 exited with code 1
```

Unsure how to proceed

### PR DESCRIPTION
**Pull request by nikuya3**

### CODE REVIEW

**Comment by nikuya3** [comment]
@turboderp would it be possible to move `exllama_sessions` from the home directory to the `exllama` directory? This makes more sense in my opinion.

**Comment by turboderp** [comment]
I added an option to specify a different directory for storing sessions. Maybe it makes sense for docker, idk. But generally storing user data in the application directory isn't a good idea, I think. For now that directory reflects the repo, and eventually it may turn into a library and/or pip package stored somewhere in a conda environment, which is not a good place to start putting potentially sensitive information by default. I think.

Also, thinking about it I'm not really sure how the docker image running in user mode could ever take ownership of files that don't already belong to the user? I guess running in root would solve it, but idk. I'll pull the changes, just let me know if you want to add in the --sessions-dir argument so I can squash it into a single commit.

**Comment by nikuya3** [comment]
You're actually correct, storing user data in the application directory is not what I wanted to go for, just a configurable directory so I can set it to a standard path in the docker container. So `--sessions-dir` is a good solution.

>Also, thinking about it I'm not really sure how the docker image running in user mode could ever take ownership of files that don't already belong to the user?

Sorry, I'm not sure what you mean by that. The non-root user inside the docker container is different from the user at the host, since the container runs in an isolated namespace and has its own filesystem.

**Comment by turboderp** [comment]
Do you need to add it to the commit before I merge it?

**Comment by nikuya3** [comment]
I started a new pull request #83

**Pull request closed without merging**
