### PR TITLE
Fixed: batching lead to faulty results, crashes and men wielding bananas.

### PR DESCRIPTION
**Pull request by aljungberg**
Without this fix, the rotary embedding code had a buffer overrun for the rotation coefficient tables which would lead to incorrect results and sometimes `CUDA error: an illegal memory access was encountered`. The reason is that we were viewing the input as `position * number of heads` rows of head dimension elements each, assuming a single batch. When we had processed all rows for a position, we "incremented" (in a manner of speaking) the position and kept going, without checking if we crossed into the next batch. So in the best case we would apply the wrong rotary embedding for batch 1, pos 0 forward, worst case we'd try to apply an embedding for position 2049, which we never generated.

The fix is to stick each batch in its own cuda block and do the right number of rows per batch. One could instead have taken the modulus to find the correct positional ordinal (assuming a contiguous x over the batch dimension), but this solution seemed cleaner.

This PR also adds a batch generation validator.

## Before

In the test below using Llama 13B, the first 4 generations should be identical, being greedy sampling on the exact same input, just done in batch. But they are not. Also note the poor quality generations like "The 196000000" -- this is likely caused by garbled positional embeddings messing with the model's reading comprehension.

 0. 'When you have eliminated the impossible, whatever remains, ... however improbable, must be the truth.\nThe first thing to do is to get the'
 1. 'When you have eliminated the impossible, whatever remains, ... however improbable, whatever remains, however improbable, however improbable, however impro'
 2. 'When you have eliminated the impossible, whatever remains, ... however, there is no other explanation.\nThe 196000000'
 3. 'When you have eliminated the impossible, whatever remains, ... however improbable it may be, must be the truth.\nThe first step in the scientific'
 4. 'When you have eliminated the impossible, whatever remains, must be considered ... the impossible.\nThe first step is to get the data.\nThe second step is to eliminate'
 5. 'When you have eliminated the impossible, whatever remains, ought to be ... the truth.\nThe only thing that is impossible is the impossible.\nThe only thing that is'
 6. 'When you have eliminated the impossible, whatever remains, (and some scholars say this is ... the impossible, however improbable, must be the truth.\nThe first thing to do is'
 7. 'When you have eliminated the impossible, whatever remains, however improbable, is a banana. ...\nA man with a banana.\nA man with a banana.\nA man with'

## After

With the fix in place, the first 4 generations are identical as expected. The remaining 4 indicate better understanding of what went before them. The model is now more skeptical about the banana's place in contemporary Conan Doyle literary analysis.

  0. 'When you have eliminated the impossible, whatever remains, ... however improbable, must be the truth.\nThe first thing to do is to get the'
 1. 'When you have eliminated the impossible, whatever remains, ... however improbable, must be the truth.\nThe first thing to do is to get the'
 2. 'When you have eliminated the impossible, whatever remains, ... however improbable, must be the truth.\nThe first thing to do is to get the'
 3. 'When you have eliminated the impossible, whatever remains, ... however improbable, must be the truth.\nThe first thing to do is to get the'
 4. 'When you have eliminated the impossible, whatever remains, must be considered ... the truth.\nThe first thing to do is to eliminate the impossible.\nThe second thing to'
 5. 'When you have eliminated the impossible, whatever remains, ought to be ... the truth.\nThe first thing to do is to get rid of the idea that the word "'
 6. 'When you have eliminated the impossible, whatever remains, (and some scholars say this is ... the most important part of the quote) must be the truth.\nThe quote is often attributed to'
 7. 'When you have eliminated the impossible, whatever remains, however improbable, is a banana. ...\nI\'m not a fan of the "banana" theory. I think it\'s'

Refs #50.

### CODE REVIEW

**Comment by turboderp** [comment]
This is great. I was meaning to get around to fixing batched inference but stuff just keeps getting in the way.

I'm a little puzzled that it works, though, since `cuda_ext.exllama_ext.rope_` is also called in `ExLlamaAttention.forward`, i.e. the non-fused attention. And it shouldn't even call `q4_attn` if the hidden states have more than one row. Hmmmmm.

**Comment by aljungberg** [comment]
> This is great. I was meaning to get around to fixing batched inference but stuff just keeps getting in the way.

Yeah, this wasn't exactly on my roadmap either! I was writing a better benchmarking tool and using a larger batch size is a great way to expose strengths and weaknesses. In my case, exllama is CPU limited for some reason so I wanted to see what it could do with less kernel launch overhead. But it crashed and sometimes I just have to fix things. (I'm like a bad guided missile, I work relentlessly towards random targets.)

> 
> I'm a little puzzled that it works, though, since `cuda_ext.exllama_ext.rope_` is also called in `ExLlamaAttention.forward`, i.e. the non-fused attention. And it shouldn't even call `q4_attn` if the hidden states have more than one row. Hmmmmm.

Yep, I didn't see `fused` being used for batching, just like you say. Still, it didn't seem to hurt to put a fix in there too for future use. I tested that it works with batch size 1 with no change to perplexity, so although I can't guarantee the fix works (since this code path isn't exercised), it's at least no worse than before.

The `ExLlamaAttention.forward` path is fixed by the change to `cuda_ext.exllama_ext.rope_`, and the fused attention is fixed by forwarding the batch size to `rope_cuda` in `q4_attn.cu` (theoretically 🤞).

**Comment by turboderp** [comment]
So I'm testing it on 7B and 13B with no issues, but 33B is acting weird.

```
 1. 'When you have eliminated the impossible, whatever remains, ... # packageeign The # The When the, When the, the When When the When the When'
 2. 'When you have eliminated the impossible, whatever remains, ... # packageeign The # The When the, When the, the When When the When the When'
 3. 'When you have eliminated the impossible, whatever remains, ... # packageeign The # The When the, When the, the When When the When the When'
 4. 'When you have eliminated the impossible, whatever remains, ... # packageeign The # The When the, When the, the When When the When the When'
 5. 'When you have eliminated the impossible, whatever remains, must be considered ....\n When The,, the, the, the, the, the, the, the,'
 6. 'When you have eliminated the impossible, whatever remains, ought to be ... When When the,\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n'
 7. 'When you have eliminated the impossible, whatever remains, (and some scholars say this is ... the meaning of the word "Torah") is the Torah.\nThe Torah is'
 8. "When you have eliminated the impossible, whatever remains, however improbable, is a banana. ...\nI'm not sure if I'm a fan of the new look. I'm"
```

The last two sequences in the batch seem to be okay, though. I don't think it has to do with splitting across GPUs, because i can split 7B and 13B and still get sensible results. Must be something to do with the dimension.

**Comment by aljungberg** [comment]
Hmm wow certainly looks like the quality goes up as batch size goes down Sounds like maybe there's still some edge case where we read or write out of bounds? Something about divisibility with the number of heads, 52? Probably too late at night for me to spot it right now. Agree, highly mysterious, though!

**Comment by turboderp** [comment]
Yeah I have to call it quits today too. I've tried with all the various tuning parameters, avoiding half2, forcing SDP attention, skipping the fused MLP... none of which should make a difference, and it doesn't. But I'll try again tomorrow.

**Comment by turboderp** [comment]
Okay, so I tried splitting the batch in the attention function, applying RoPE to each sequence individually and rebuilding the batch afterwards, and there is no difference. I also brought back the PyTorch RoPE function from a much earlier version and it behaves exactly the same. So I don't think the problem is with the positional embeddings.

It works with 8 identical sequences in a batch, though, which is telling. Even more telling, with 7 identical sequences and a single different one at the end, the last one ends up correct (presumably) while the first 7 are messed up. It doesn't appear that the order matters, either, if I make the unique sequence the first one in the batch.

I also saw it on a 7B model, so I don't think it has to do with dimension after all. There's obviously a broadcasting error somewhere, a place where it's implicitly assuming bsz == 1, so bsz * q_len == q_len.

**Comment by aljungberg** [comment]
Yeah I just double-checked the rope kernel myself to verify we're getting complete coverage (hitting all the rows, using the right position for each) and although I just had a short time to play with it, it looked fine, with and without `past_len`.

The fact that identical generations work gives me the idea that maybe some operation is reading or writing the wrong batch (presumably always going for batch 0) , maybe in the cache or something. So as long as the generations are identical, it doesn't matter which batch state you reference since they're all the same anyhow.

**Comment by turboderp** [comment]
Here's something, I think. Adding `ids = ids[:, 10:]` before generating, to crop out the padding tokens, I at least get consistent output regardless of the ordering:

```
 1. 'eliminated the impossible, whatever remains, must be considered ... as the truth.\nSherlock Holmes, the famous fictional detective, used this'
 2. 'eliminated the impossible, whatever remains, ought to be ... the truth.\nSherlock Holmes: Elementary, my dear Watson.'
 3. 'When you have eliminated the impossible, whatever remains, ... however improbable, must be the truth.\nSherlock Holmes, The Sign of'
 4. 'When you have eliminated the impossible, whatever remains, ... however improbable, must be the truth.\nSherlock Holmes, The Sign of'
 5. 'remains, (and some scholars say this is ... the most likely scenario), that the church was built on the site of the palace of Caiaphas'
 6. ', however improbable, is a banana. ...\nThe banana is a fruit that is not only delicious but also very healthy. It'
 7. 'When you have eliminated the impossible, whatever remains, ... however improbable, must be the truth.\nSherlock Holmes, The Sign of'
 8. 'When you have eliminated the impossible, whatever remains, ... however improbable, must be the truth.\nSherlock Holmes, The Sign of'
 
 1. 'When you have eliminated the impossible, whatever remains, ... however improbable, must be the truth.\nSherlock Holmes, The Sign of'
 2. 'When you have eliminated the impossible, whatever remains, ... however improbable, must be the truth.\nSherlock Holmes, The Sign of'
 3. 'When you have eliminated the impossible, whatever remains, ... however improbable, must be the truth.\nSherlock Holmes, The Sign of'
 4. 'When you have eliminated the impossible, whatever remains, ... however improbable, must be the truth.\nSherlock Holmes, The Sign of'
 5. 'eliminated the impossible, whatever remains, must be considered ... as the truth.\nSherlock Holmes, the famous fictional detective, used this'
 6. 'eliminated the impossible, whatever remains, ought to be ... the truth.\nSherlock Holmes: Elementary, my dear Watson.'
 7. 'remains, (and some scholars say this is ... the most likely scenario), that the church was built on the site of the palace of Caiaphas'
 8. ', however improbable, is a banana. ...\nThe banana is a fruit that is not only delicious but also very healthy. It'
 
 1. 'When you have eliminated the impossible, whatever remains, ... however improbable, must be the truth.\nSherlock Holmes, The Sign of'
 2. 'eliminated the impossible, whatever remains, must be considered ... as the truth.\nSherlock Holmes, the famous fictional detective, used this'
 3. 'eliminated the impossible, whatever remains, ought to be ... the truth.\nSherlock Holmes: Elementary, my dear Watson.'
 4. 'remains, (and some scholars say this is ... the most likely scenario), that the church was built on the site of the palace of Caiaphas'
 5. ', however improbable, is a banana. ...\nThe banana is a fruit that is not only delicious but also very healthy. It'
 6. 'When you have eliminated the impossible, whatever remains, ... however improbable, must be the truth.\nSherlock Holmes, The Sign of'
 7. 'When you have eliminated the impossible, whatever remains, ... however improbable, must be the truth.\nSherlock Holmes, The Sign of'
 8. 'When you have eliminated the impossible, whatever remains, ... however improbable, must be the truth.\nSherlock Holmes, The Sign of'

 1. 'eliminated the impossible, whatever remains, must be considered ... as the truth.\nSherlock Holmes, the famous fictional detective, used this'
 2. 'When you have eliminated the impossible, whatever remains, ... however improbable, must be the truth.\nSherlock Holmes, The Sign of'
 3. 'When you have eliminated the impossible, whatever remains, ... however improbable, must be the truth.\nSherlock Holmes, The Sign of'
 4. 'When you have eliminated the impossible, whatever remains, ... however improbable, must be the truth.\nSherlock Holmes, The Sign of'
 5. 'When you have eliminated the impossible, whatever remains, ... however improbable, must be the truth.\nSherlock Holmes, The Sign of'
 6. 'eliminated the impossible, whatever remains, ought to be ... the truth.\nSherlock Holmes: Elementary, my dear Watson.'
 7. 'remains, (and some scholars say this is ... the most likely scenario), that the disciples were mistaken about the resurrection, then the'
 8. ', however improbable, is a banana. ...\nThe banana is a fruit that is not only delicious but also very healthy. It'
```

Which... leads me to notice that it's not doing anything to mask out the padding tokens during attention.

**Comment by turboderp** [comment]
Yeah, definitely need to mask out the padding:

```
                attn_mask = torch.zeros(batch_size, 1, seq_len, past_len + seq_len, dtype = torch.float16, device = devs[0])
                attn_mask_triu = torch.triu(torch.full((seq_len - 1, seq_len - 1), torch.finfo(torch.float16).min))
                attn_mask[:, :, : seq_len - 1, past_len + 1: past_len + seq_len] = attn_mask_triu

                for seq in range(batch_size):
                    padding_len = 0
                    while padding_len < seq_len and input_ids[seq, padding_len].item() == 0:
                        padding_len += 1
                    if padding_len > 0:
                        attn_mask[seq, :, :, :padding_len] = torch.finfo(torch.float16).min
```

Not sure if there's a way to still use `is_causal = True` in `scaled_dot_product_attention`.

**Comment by aljungberg** [comment]
Nice catch! Can confirm, fixing this leads to normal looking generations. I'm pushing the most obvious quick and dirty fix: padding with spaces instead.

Super strange symptoms, like why would 33B find token 0 more attention-worthy? And even if it does, why'd it jump between batches? But you're totally right. My bad. The model forward method doesn't accept an attention mask so I just put int zeroes and crossed my fingers. Should have checked.

Regarding the correct way to do it, in transformers you can specify the special token -100, AFAIK, to have it be masked out in the automatically generated mask. Also you can give it an attention mask.

**Comment by aljungberg** [comment]
Generation using 33B with the quick and dirty fix:

```
 ** Batching sanity check: 1-4 should be identical. All should be reasonable for the model you're using.

 1. '                    When you have eliminated the impossible, whatever remains, ... however improbable, must be the truth.\n> \n> \n> \n'
 2. '                    When you have eliminated the impossible, whatever remains, ... however improbable, must be the truth.\n> \n> \n> \n'
 3. '                    When you have eliminated the impossible, whatever remains, ... however improbable, must be the truth.\n> \n> \n> \n'
 4. '                    When you have eliminated the impossible, whatever remains, ... however improbable, must be the truth.\n> \n> \n> \n'
 5. "              When you have eliminated the impossible, whatever remains, must be considered ... as the truth.\n\nComment: @JonathanLeffler: I'm not"
 6. "              When you have eliminated the impossible, whatever remains, ought to be ... the truth.\n\nComment: @JonathanLeffler: I'm not sure"
 7. '  When you have eliminated the impossible, whatever remains, (and some scholars say this is ... the most important part of the quote) however improbable, must be the truth.\n\n'
 8. "When you have eliminated the impossible, whatever remains, however improbable, is a banana. ...\nI'm not sure if I'm a fan of the new look. I'm"
 ```

**Comment by turboderp** [comment]
I'm not fully understanding it either. The models probably have a different embedding vector for token 0, but I tried just  setting that to all zeros, which as I understand it _should_ have the same effect as masking it out, but it doesn't. Maybe I'm overlooking something, and maybe the attention mask fix just masks another bug somewhere.

Anyway, I'll include it as is for now, then maybe add a utility function to generate a mask for padded sequences, along with a nice way of passing it to the model.

**Comment by aljungberg** [comment]
Maybe the 33B model was accidentally trained on some padding tokens, but it was rare in the training data and so became a very strong signal to generate something particular?

Yeah, agree that setting the embedding of token 0 to all zeroes should bring you pretty close to something that won't be attended, since the dot product of a zero vector and any vector is zero. And the rotary embeddings are multiplicative, not additive, so should not get in the way of that... Hmm, I guess there might be a bias term in the linear projection going into the attention that could turn it into something non-zero? As far as I remember there's no bias in the Llama projections though. Would have to double-check.

The quantisation might affect it, making it less clean mathematically. Quantisation might transform `0 * <something>` into `<almost zero> * <something>`?  I mean this is an interesting puzzle in its own right. Not sure if it's worth pursuing, but it could lead to finding some other bug somewhere. A lot of discoveries start with "hmm, that's funny".

And, to emphasise this again, the other thing that doesn't sit right with me is that one of the identical prompts generated a different continuation in your testing. Even if the model attends to these padding tokens, you don't attend to other batches! So whatever it does it should do repeatably for each batch.

**Comment by turboderp** [comment]
Yep, there's no bias anywhere, so a zero embedding should just remain zero throughout. It seems like that's also the case. But it suddenly occurs to me that attention uses softmax normalization, so there's an implicit exponentiation there. To actually get zero attention on a token you'd need a dot product of -inf. I don't think there's a way for an embedding to produce a key that reliably creates a negative dot product with any query. Maybe the query is usually mostly positive? Idk. I imagine it's the sort of thing that could differ between models, though.

As for the difference in output, the forward pass is never _entirely_ deterministic due to how the quantized matmul works, relying on `atomicAdd` instead of reduction. It doesn't normally make a big difference, even with FP16, but it might be amplified by whatever weird state results from attending to padding tokens.

With `-mmrt 1` it falls back on cuBLAS, and I think the cuBLAS matmul is deterministic. I guess that's worth testing.

**Pull request merged**
