### PR TITLE
Add docker support

### PR DESCRIPTION
**Pull request by nikuya3**
Adds the option to run the web UI using docker. Currently only works for nvidia gpus.

### CODE REVIEW

**Comment by turboderp** [comment]
Looks good. Just a couple of comments:

- I'm not very familiar with docker, but is there a place to add additional command line arguments? There are some that would be needed for compatibility and for multi-GPU support.
- I'm thinking maybe it's better if it pulls a specific version of PyTorch that works well (like the current one) instead of the latest nightly?

**Comment by nikuya3** [comment]
1. Yes, it's possible to add new command line arguments in the `command` field of `docker-compose.yml` (or `docker-compose.override.yml`)! For example:
```yaml
services:
  web:
    command: |
      --host 0.0.0.0:5000
      --gpu_split 20,7,7
      --no_half2
```

If you run the container manually, you can simply append the command line arguments to the `docker run` command, like:
```
docker run --gpus all -p 5000:5000 -v <path_to_model_files>:/app/model/ --rm -it exllama-web \
  --host 0.0.0.0:5000
  --gpu_split 20,7,7
  --no_half2
```

The arguments are passed via `entrypoint.sh` to `webui/app.py`.

2. I agree that it makes more sense to specify a specific version of pytorch. Are you using any features from 2.1.0 that are not available in 2.0.1? If not, then I would use 2.0.1, otherwise I would specify the latest nightly version (2.1.0.dev20230610+cu118).

Btw, are you using/planning to use `torchvision` and/or `torchaudio`? I don't think they're referenced in the code. If not, then I would remove them.

**Comment by turboderp** [comment]
I just left `torchvision` and `torchaudio` in the readme because that's the command line the PyTorch website spits out to install the latest nightly build. I'm definitely not using them and I don't think they're referenced anywhere in the code, so you should just leave them out. I've also had no problems so far running 2.0.1 on RunPod, so yeah, that's probably a good default for the docker setup.

**Comment by nikuya3** [comment]
ok, will do!

**Pull request merged**
