### PR TITLE
New API endpoint 

### PR DESCRIPTION
**Pull request by jisungk2**
Created API endpoint /api/inputoutput to manually store user input and bot output in current session history

### CODE REVIEW

**Comment by turboderp** [comment]
I'm unsure what the use case is for this?

**Comment by jmoney7823956789378** [comment]
Maybe a bot?
I use this discord bot https://github.com/chrisrude/oobabot with ooba's ui/api currently.

**Comment by jisungk2** [comment]
I'm using it for my own project where some of the bot response I receive do not rely on exllama but I still wanna keep it in exllama history so I can ask the bot about it again.

**Comment by turboderp** [comment]
I see. I can't really add it as is, though, with the hard-coded bot name and all. I added something equivalent instead that's a little more general but should work just as well. You'd have to call it twice, once with a request:

    { text: <your user input> }  // default author is the user name or None if running in freeform mode

Then with:

    { author: "Chatbort", text: <your bot output> }
    
I haven't tested it, but it should work. Let me know if there are any issues with it.

**Comment by jisungk2** [comment]
that looks good to me!

**Pull request closed without merging**
